import {asString} from '../asString';

const check = (str: string) => {
  expect(asString(str)).toBe(JSON.stringify(str));
  expect(JSON.parse(asString(str))).toBe(str);
};

const generateStr = (): string => {
  let str = '';
  for (let i = 0; i < 5; i++) str += String.fromCodePoint(Math.round(Math.random() * 0x6ffff));
  return str;
};

test('encodes the same as JSON.stringify()', () => {
  check('');
  check('"');
  check("'");
  check('asdf');
  check('asdfasdfasdfasdfsadfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfsadfasdfasdfasdf');
  check('🍻');
  check('👩‍👩‍👦‍👦');
  check('Лексилогос');
  check('\b');
  check('\b\t\0');
  check('\0');
  check('\f');
  check('\r');
  check('\n');
});

test('encodes the same as JSON.stringify(), autogenerated', () => {
  for (let i = 0; i < 10000; i++) check(generateStr());
});
