import type {SheetFieldOptions} from '../types';

export const defaultSheet: SheetFieldOptions = {
  segments: 800,
  columns: 300,
  length: 4.4,
  width: 1.5,
  forward: [1.5, 0, 0.5],
  tilt: 0.45,
  taper: 0.12,
  twistBase: 0,
  twistTurns: 0.55,
  twistWave: 0.12,
  twistFreq: 2,
  twistSpeed: 0.2,
  foldAmp: 0.3,
  foldLateral: 0.08,
  foldFreq: 1.3,
  foldSpeed: 0.3,
  shapeOctaves: 3,
  shapeRoughness: 0.6,
  flowScale: 1,
  pulse: 0,
  pulseSpeed: 0.5,
  colorMode: 'gradient',
  color: {wave: 0.05, waveFreq: 0.8, waveSpeed: 0.2},
  colorAlong: 0.9,
  colorAcross: 0.12,
  colorActive: 4,
  colorChangeSpeed: 1,
  fibers: true,
  fiberCount: 220,
  fiberContrast: 0.35,
  fiberShear: 0.3,
  fiberDrift: 0.03,
  fiberSharpness: 4,
  fiberJitter: 0.45,
  fiberVariation: 0.55,
  fiberGaps: 0.3,
  fiberGlint: 0.5,
  light: true,
  ambient: 0.58,
  diffuse: 0.6,
  specular: 0.15,
  shininess: 11,
  rim: 0.98,
  rimPower: 3,
  lightDir: [0.2, 0.6, 0.7],
  lightFollowsMouse: true,
  fog: 0,
  glow: 0,
  vignette: 0.1,
  opacity: 1,
  additive: false,
  yawSpeed: 0,
  pitchAmp: 0,
  pitchSpeed: 0.2,
  perspective: 7,
  radius: 1,
  centerDrift: 0,
  centerDriftSpeed: 0.4,
  reactToMouse: true,
  tiltMax: 0.2,
  followMouse: true,
  followStrength: 0.05,
  followReach: 0.4,
  bendMouse: false,
  bendRadius: 160,
  bendStrength: 50,
};
