import type {TsNode} from './types';

export const TAB = '  ';

export const keywords = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'as',
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield',
  'any',
  'boolean',
  'constructor',
  'declare',
  'get',
  'module',
  'require',
  'number',
  'set',
  'string',
  'symbol',
  'type',
  'from',
  'of',
  'unknown',
]);

export const normalizeKey = (prop: string): string =>
  /^[a-z_][a-z_0-9]*$/i.test(prop) && !keywords.has(prop) ? prop : JSON.stringify(prop);

export const isSimpleType = ({node}: TsNode): boolean =>
  node === 'NumberKeyword' || node === 'StringKeyword' || node === 'BooleanKeyword';
