import * as React from 'react';
import {ArgsPane, type ArgsPaneProps} from './index';
import {Iconista} from '../../../icons/Iconista';
import type {Meta, StoryObj} from '@storybook/react-webpack5';

const action =
  (name: string) =>
  (...args: unknown[]) =>
    console.log(name, ...args);

const meta: Meta = {
  title: '4. Card/ContextMenu/ArgsPane',
  component: ArgsPane,
  parameters: {
    layout: 'centered',
  },
};

export default meta;

export const Default: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Open Link',
      compact: true,
    },
    params: [
      {
        kind: 'str',
        id: 'note',
        name: 'Note',
        placeholder: 'Optional note…',
      },
      {
        kind: 'bool',
        id: 'poster',
        name: 'Use as poster',
        description: 'Whether to use the link as a poster',
        optional: false,
      },
      {
        kind: 'bool',
        id: 'private',
        name: 'Private',
        default: true,
      },
      {
        kind: 'num',
        id: 'size',
        name: 'Size',
        optional: true,
        placeholder: 'Size in MB',
        default: 10,
      },
      {
        kind: 'color',
        id: 'color',
        name: 'Color',
        optional: true,
        default: '#0077ff',
      },
      {
        kind: 'select',
        id: 'quality',
        name: 'Quality',
        optional: true,
        default: 'medium',
        options: [
          {name: 'low', display: () => 'Low'},
          {name: 'medium', display: () => 'Medium'},
          {name: 'high', display: () => 'High'},
        ],
      },
    ],
  },
};

const timezones = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Anchorage',
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Moscow',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Bangkok',
  'Asia/Shanghai',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Australia/Sydney',
  'Pacific/Auckland',
  'Pacific/Honolulu',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Africa/Lagos',
];

const fontFamilies = [
  'Arial',
  'Helvetica',
  'Times New Roman',
  'Georgia',
  'Verdana',
  'Trebuchet MS',
  'Courier New',
  'Lucida Console',
  'Monaco',
  'Menlo',
  'Consolas',
  'SF Mono',
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Source Code Pro',
  'Fira Code',
  'JetBrains Mono',
  'IBM Plex Sans',
  'Noto Sans',
  'Ubuntu',
  'Raleway',
  'Playfair Display',
  'Merriweather',
  'Oswald',
  'Nunito',
  'PT Sans',
];

export const Interactive: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Create Event',
      compact: true,
    },
    onSubmit: action('onSubmit'),
    onCancel: action('onCancel'),
    params: [
      {
        kind: 'str',
        id: 'title',
        name: 'Title',
        placeholder: 'Event title…',
      },
      {
        kind: 'str',
        id: 'description',
        name: 'Description',
        placeholder: 'Describe the event…',
        optional: true,
      },
      {
        kind: 'bool',
        id: 'allDay',
        name: 'All day',
        description: 'Event spans the entire day',
        default: false,
      },
      {
        kind: 'num',
        id: 'duration',
        name: 'Duration (min)',
        placeholder: 'Duration in minutes',
        default: 60,
      },
      {
        kind: 'color',
        id: 'color',
        name: 'Label Color',
        default: '#ff5722',
      },
      {
        kind: 'select',
        id: 'timezone',
        name: 'Timezone',
        default: 'UTC',
        options: timezones.map((tz) => ({name: tz, display: () => tz})),
      },
      {
        kind: 'select',
        id: 'repeat',
        name: 'Repeat',
        optional: true,
        default: 'none',
        options: [
          {name: 'none', display: () => 'None'},
          {name: 'daily', display: () => 'Daily'},
          {name: 'weekly', display: () => 'Weekly'},
          {name: 'biweekly', display: () => 'Every 2 weeks'},
          {name: 'monthly', display: () => 'Monthly'},
          {name: 'yearly', display: () => 'Yearly'},
        ],
      },
      {
        kind: 'bool',
        id: 'notify',
        name: 'Send notifications',
        default: true,
      },
    ],
  },
};

export const LiveTweaks: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Tweak',
      compact: true,
    },
    onChange: action('onChange'),
    onCancel: action('onCancel'),
    params: [
      {
        kind: 'num',
        id: 'fontSize',
        name: 'Font Size',
        default: 16,
        defaultable: true,
        initialDef: false,
        min: 6,
        max: 96,
        dragSensitivity: 0.25,
        dragAxis: 'y',
      },
      {
        kind: 'color',
        id: 'textColor',
        name: 'Text Color',
        default: '#1a1a1a',
        defaultable: true,
        initialDef: false,
      },
      {
        kind: 'bool',
        id: 'italic',
        name: 'Italic',
        defaultable: true,
      },
    ],
  },
};

export const LongSelectList: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Paragraph Settings',
      compact: true,
    },
    onSubmit: action('onSubmit'),
    onCancel: action('onCancel'),
    params: [
      {name: 'Metadata', heading: true, collapsible: true, initialCollapsed: true},
      {
        kind: 'select',
        id: 'blockType',
        name: 'Block Type',
        default: 'paragraph',
        searchPlaceholder: 'Find block type…',
        icon: () => <Iconista width={15} height={15} set="bootstrap" icon="type-h1" />,
        options: [
          {name: 'Paragraph', id: 'paragraph'},
          {name: 'Heading 1', id: 'h1'},
          {name: 'Heading 2', id: 'h2'},
          {name: 'Heading 3', id: 'h3'},
          {name: 'Heading 4', id: 'h4'},
          {name: 'Blockquote', id: 'blockquote'},
          {name: 'Code block', id: 'code'},
          {name: 'Ordered list', id: 'ol'},
          {name: 'Unordered list', id: 'ul'},
        ],
      },
      {
        kind: 'str',
        id: 'label',
        name: 'Label',
        optional: true,
        placeholder: 'Section label',
        icon: () => <Iconista width={15} height={15} set="tabler" icon="tag" />,
      },
      {
        kind: 'str',
        id: 'anchor',
        name: 'Anchor',
        optional: true,
        placeholder: 'my-section',
        icon: () => <Iconista width={15} height={15} set="tabler" icon="anchor" />,
      },
      {
        kind: 'str',
        id: 'language',
        name: 'Language',
        optional: true,
        placeholder: 'en',
        icon: () => <Iconista width={15} height={15} set="tabler" icon="language" />,
      },
      {
        kind: 'enum',
        id: 'direction',
        name: 'Direction',
        default: 'ltr',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="tabler" icon="directions" />,
        options: [
          {
            name: 'Left to right',
            id: 'ltr',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-left" />,
          },
          {
            name: 'Right to left',
            id: 'rtl',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-right" />,
          },
        ],
      },
      {
        kind: 'select',
        id: 'role',
        name: 'Role',
        optional: true,
        searchPlaceholder: 'Find role…',
        icon: () => <Iconista width={15} height={15} set="tabler" icon="universe" />,
        options: [
          {name: 'article', id: 'article'},
          {name: 'aside', id: 'aside'},
          {name: 'figure', id: 'figure'},
          {name: 'nav', id: 'nav'},
          {name: 'region', id: 'region'},
          {name: 'main', id: 'main'},
        ],
      },
      {
        kind: 'str',
        id: 'cssClasses',
        name: 'CSS classes',
        optional: true,
        placeholder: 'class-a class-b',
        icon: () => <Iconista width={15} height={15} set="radix" icon="code" />,
      },
      {
        kind: 'bool',
        id: 'hidden',
        name: 'Hidden',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="eye-off" />,
      },
      {name: 'Font', heading: true, collapsible: true},
      {
        kind: 'select',
        id: 'fontFamily',
        name: 'Typeface',
        default: 'Inter',
        defaultable: true,
        searchPlaceholder: 'Find font…',
        icon: () => <Iconista width={15} height={15} set="radix" icon="font-family" />,
        options: fontFamilies.map((f) => ({name: f, display: () => f})),
      },
      {
        kind: 'num',
        id: 'fontSize',
        name: 'Font Size',
        default: 16,
        defaultable: true,
        initialDef: false,
        min: 6,
        max: 96,
        dragSensitivity: 0.25,
        dragAxis: 'y',
        icon: () => <Iconista width={15} height={15} set="radix" icon="font-size" />,
      },
      {
        kind: 'num',
        id: 'fontStretch',
        name: 'Font stretch',
        default: 100,
        defaultable: true,
        min: 50,
        max: 200,
        step: 5,
        dragSensitivity: 0.5,
        icon: () => <Iconista width={15} height={15} set="tabler" icon="stretching" />,
      },
      {
        kind: 'bool',
        id: 'opticalSizing',
        name: 'Optical sizing',
        default: true,
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="glasses" />,
      },
      {
        kind: 'select',
        id: 'ligatures',
        name: 'Ligatures',
        default: 'common',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="ligature" />,
        options: [
          {name: 'None', id: 'none', icon: () => <Iconista width={14} height={14} set="lucide" icon="ban" />},
          {name: 'Common', id: 'common', icon: () => <Iconista width={14} height={14} set="lucide" icon="ligature" />},
          {
            name: 'Discretionary',
            id: 'discretionary',
            icon: () => <Iconista width={14} height={14} set="lucide" icon="sparkles" />,
          },
          {
            name: 'Historical',
            id: 'historical',
            icon: () => <Iconista width={14} height={14} set="lucide" icon="scroll" />,
          },
        ],
      },
      {
        kind: 'enum',
        id: 'numericVariant',
        name: 'Numeric variant',
        default: 'default',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="hash" />,
        options: [
          {name: 'Default', id: 'default', icon: () => <Iconista width={14} height={14} set="lucide" icon="hash" />},
          {
            name: 'Oldstyle',
            id: 'oldstyle',
            icon: () => <Iconista width={14} height={14} set="lucide" icon="feather" />,
          },
          {name: 'Lining', id: 'lining', icon: () => <Iconista width={14} height={14} set="lucide" icon="rows-2" />},
          {name: 'Tabular', id: 'tabular', icon: () => <Iconista width={14} height={14} set="lucide" icon="table" />},
        ],
      },
      {name: 'Spacing', heading: true, collapsible: true},
      {
        kind: 'num',
        id: 'lineHeight',
        name: 'Line Height',
        default: 1.5,
        defaultable: true,
        min: 0.5,
        max: 3,
        step: 0.1,
        dragSensitivity: 0.01,
        dragAxis: 'y',
        icon: () => <Iconista width={15} height={15} set="radix" icon="line-height" />,
      },
      {
        kind: 'num',
        id: 'letterSpacing',
        name: 'Letter Spacing',
        default: 0,
        defaultable: true,
        min: -10,
        max: 20,
        dragSensitivity: 0.1,
        icon: () => <Iconista width={15} height={15} set="radix" icon="letter-spacing" />,
      },
      {
        kind: 'num',
        id: 'wordSpacing',
        name: 'Word Spacing',
        default: 0,
        defaultable: true,
        min: -10,
        max: 40,
        dragSensitivity: 0.2,
        icon: () => <Iconista width={15} height={15} set="radix" icon="letter-spacing" />,
      },
      {
        kind: 'enum',
        id: 'kerning',
        name: 'Kerning',
        default: 'auto',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="tabler" icon="kerning" />,
        options: [
          {name: 'Auto', id: 'auto', icon: () => <Iconista width={14} height={14} set="lucide" icon="wand-sparkles" />},
          {name: 'Normal', id: 'normal', icon: () => <Iconista width={14} height={14} set="lucide" icon="equal" />},
          {name: 'None', id: 'none', icon: () => <Iconista width={14} height={14} set="lucide" icon="ban" />},
        ],
      },
      {name: 'Style', heading: true, collapsible: true},
      {
        kind: 'num',
        id: 'fontWeight',
        name: 'Font weight',
        default: 400,
        defaultable: true,
        min: 100,
        max: 900,
        step: 100,
        dragSensitivity: 4,
        icon: () => <Iconista width={15} height={15} set="radix" icon="font-bold" />,
      },
      {
        kind: 'bool',
        id: 'italic',
        name: 'Italic',
        defaultable: true,
        initialDef: false,
        initialValue: true,
        icon: () => <Iconista width={16} height={16} set="lucide" icon="italic" />,
      },
      {
        kind: 'bool',
        id: 'largeCaps',
        name: 'Large caps',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="radix" icon="letter-case-uppercase" />,
      },
      {
        kind: 'bool',
        id: 'smallCaps',
        name: 'Small caps',
        defaultable: true,
        default: true,
        icon: () => <Iconista width={15} height={15} set="radix" icon="letter-case-lowercase" />,
      },
      {
        kind: 'num',
        id: 'underlineOffset',
        name: 'Underline offset',
        default: 2,
        defaultable: true,
        min: 0,
        max: 12,
        step: 0.5,
        dragSensitivity: 0.05,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="underline" />,
      },
      {
        kind: 'num',
        id: 'decorationThickness',
        name: 'Decoration thickness',
        default: 1,
        defaultable: true,
        min: 0.5,
        max: 6,
        step: 0.5,
        dragSensitivity: 0.03,
        icon: () => <Iconista width={15} height={15} set="lucide" icon="highlighter" />,
      },
      {name: 'Color', heading: true, collapsible: true},
      {
        kind: 'color',
        id: 'textColor',
        name: 'Text Color',
        default: '#1a1a1a',
        defaultable: true,
        initialDef: false,
        icon: () => <Iconista width={16} height={16} set="lucide" icon="paintbrush" />,
      },
      {
        kind: 'color',
        id: 'bgColor',
        name: 'Background',
        default: '#ffffff',
        defaultable: true,
        alpha: true,
        icon: () => <Iconista width={16} height={16} set="lucide" icon="paint-bucket" />,
      },
      {name: 'Alignment', heading: true, collapsible: true},
      {
        kind: 'enum',
        id: 'textAlign',
        name: 'Text Align',
        default: 'left',
        defaultable: true,
        icon: () => <Iconista width={15} height={15} set="tabler" icon="pilcrow" />,
        options: [
          {
            name: 'Align left',
            id: 'left',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-left" />,
          },
          {
            name: 'Align center',
            id: 'center',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-center" />,
          },
          {
            name: 'Align right',
            id: 'right',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-right" />,
          },
          {
            name: 'Justify',
            id: 'justify',
            icon: () => <Iconista width={16} height={16} set="lucide" icon="align-justify" />,
          },
        ],
      },
      {
        kind: 'num',
        id: 'indentation',
        name: 'Indentation',
        default: 0,
        defaultable: true,
        min: 0,
        max: 8,
        dragSensitivity: 0.05,
        icon: () => <Iconista width={16} height={16} set="lucide" icon="indent-increase" />,
      },
      {name: 'Advanced', heading: true, collapsible: true, initialCollapsed: true},
      {
        kind: 'str',
        id: 'fontVariationSettings',
        name: 'Variation settings',
        optional: true,
        placeholder: '"wght" 600, "wdth" 95',
        icon: () => <Iconista width={15} height={15} set="lucide" icon="sliders-horizontal" />,
      },
      {
        kind: 'str',
        id: 'fontFeatureSettings',
        name: 'Feature settings',
        optional: true,
        placeholder: '"liga" 1, "smcp" 1',
        icon: () => <Iconista width={15} height={15} set="lucide" icon="code" />,
      },
    ],
  },
};

export const MinimalBoolOnly: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Preferences',
      compact: true,
    },
    onSubmit: action('onSubmit'),
    onCancel: action('onCancel'),
    params: [
      {
        kind: 'bool',
        id: 'darkMode',
        name: 'Dark mode',
        default: false,
      },
      {
        kind: 'bool',
        id: 'animations',
        name: 'Enable animations',
        default: true,
      },
      {
        kind: 'bool',
        id: 'sounds',
        name: 'Sound effects',
        description: 'Play sounds on interactions',
      },
      {
        kind: 'bool',
        id: 'autoSave',
        name: 'Auto-save',
        default: true,
        description: 'Automatically save changes',
      },
    ],
  },
};

export const AllOptional: StoryObj<ArgsPaneProps> = {
  args: {
    item: {
      name: 'Export Options',
      compact: true,
    },
    onSubmit: action('onSubmit'),
    onCancel: action('onCancel'),
    params: [
      {
        kind: 'str',
        id: 'filename',
        name: 'Filename',
        placeholder: 'custom-export-name',
        optional: true,
      },
      {
        kind: 'select',
        id: 'format',
        name: 'Format',
        optional: true,
        default: 'json',
        options: [
          {name: 'json', display: () => 'JSON'},
          {name: 'csv', display: () => 'CSV'},
          {name: 'xml', display: () => 'XML'},
          {name: 'yaml', display: () => 'YAML'},
          {name: 'toml', display: () => 'TOML'},
          {name: 'msgpack', display: () => 'MessagePack'},
          {name: 'protobuf', display: () => 'Protocol Buffers'},
          {name: 'avro', display: () => 'Avro'},
          {name: 'parquet', display: () => 'Parquet'},
        ],
      },
      {
        kind: 'num',
        id: 'maxRows',
        name: 'Max Rows',
        placeholder: 'Unlimited if empty',
        optional: true,
      },
      {
        kind: 'bool',
        id: 'includeHeaders',
        name: 'Include headers',
        optional: true,
        default: true,
      },
      {
        kind: 'bool',
        id: 'compress',
        name: 'Compress output',
        optional: true,
        description: 'Gzip the exported file',
      },
      {
        kind: 'color',
        id: 'highlightColor',
        name: 'Highlight Color',
        optional: true,
      },
      {
        kind: 'char',
        id: 'separator',
        name: 'Separator',
        optional: true,
        placeholder: ',',
        default: ',',
      },
      {
        kind: 'char',
        id: 'emoji',
        name: 'Marker',
        optional: true,
        emoji: true,
        placeholder: '🚀',
      },
    ],
  },
};
