export const enum Code {
  MakeObject = 0,
  MakeArray = 1,
  MakeString = 2,
  MakeNumber = 3,
  SetRoot = 4,
  SetObjectKeys = 5,
  SetNumber = 6,
  InsertStringSubstring = 7,
  InsertArrayElements = 8,
  DeleteOne = 9,
  Delete = 10,
  NoopOne = 11,
  Noop = 12,
  MakeConstant = 13,
  MakeValue = 14,
  SetValue = 15,
}
