/**
 * Static pre-render script.
 *
 * Runs after `yarn build` to inject server-rendered HTML into each dist page:
 *   yarn build && yarn prerender
 *
 * For each route in routes.ts:
 *   1. Sets the SSR pathname via NiceUiNavService (updates module-level location$ synchronously).
 *   2. Creates a PagesService so it resolves the correct page component.
 *   3. Calls renderToString(<App pages={...} />) to produce HTML.
 *   4. Collects all nano-css styles accumulated across renders (nano.raw).
 *   5. Writes dist/<route>/index.html with HTML + inlined styles.
 *
 * Run with:  ts-node --project tsconfig.prerender.json scripts/prerender.tsx
 */

import * as React from 'react';
import * as fs from 'fs';
import * as path from 'path';
import {renderToString} from 'react-dom/server';
import {nano} from 'nano-theme';
import {NiceUiNavService} from '@jsonjoy.com/ui/lib/context/services/NiceUiNavService';
import {PagesService} from '../src/services/PagesService';
import {App} from '../src/App';
import {routes} from '../routes';

const distDir = path.resolve(__dirname, '..', 'dist');
const shell = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');

// Use a single nav instance. nav.go() updates the module-level location$ /
// pathname$ / steps$ synchronously (NiceUiNavService SSR mock).
const nav = new NiceUiNavService();

const rendered: {route: string; html: string}[] = [];

for (const route of routes) {
  nav.go(route);
  const pages = new PagesService(nav);
  const html = renderToString(React.createElement(App, {pages}));
  rendered.push({route, html});
}

// nano.raw accumulates all CSS generated by nano-theme rules across all
// renders. Inject once into every page (styles are shared anyway).
const css: string = (nano as unknown as {raw: string}).raw ?? '';

for (const {route, html} of rendered) {
  let output = shell.replace('<div id="root"></div>', `<div id="root">${html}</div>`);

  if (css) {
    output = output.replace('</head>', `  <style data-nano-css>${css}</style>\n  </head>`);
  }

  const dir = route === '/' ? distDir : path.join(distDir, route);
  fs.mkdirSync(dir, {recursive: true});
  const file = path.join(dir, 'index.html');
  fs.writeFileSync(file, output);

  console.log(`prerendered  ${route.padEnd(20)} → ${path.relative(process.cwd(), file)}`);
}
