/**
 * Hunk-placement fixtures for {@link shiftDown}, measured once against GNU
 * diffutils 3.12 with `diff -d -U 999999`. `-d` (GNU's minimal mode) is the
 * reference: GNU's *default* output trades edit volume for speed on large
 * indentation-rich input and is not always minimal.
 *
 * Each entry is `[a, b, placement]`. `a` and `b` hold **one character per
 * line** — the pass only ever asks whether two lines are equal, so a character
 * alphabet reproduces every duplication pattern at a fraction of the size.
 * `placement` is GNU's op sequence over the whole file (`=` context, `-`
 * deletion, `+` insertion), which is the hunk placement with hunk splitting and
 * context noise removed.
 *
 * Generated from a seeded mixture of alphabet sizes (5 / 12 / 52 distinct
 * lines), file lengths (40 / 120) and edit rates (5% / 15%), mirroring the
 * strata the out-of-package probe corpus measures. Byte-exact agreement with
 * GNU is best-effort and deliberately not promised, so the test over these
 * asserts a floor.
 */
export const PLACEMENT: [a: string, b: string, placement: string][] = [
  [
    'ceeeabedaceaddcdbbcbbeaaaedddeeeebbabcac',
    'ceeeabedaceaddcdbbcbbea0aedddeeeebbabcac',
    '=======================-+================',
  ],
  [
    'badcbcbecedbabaabaddbbcebacacbcaeadacdeb',
    'badcbcbecedbab0aba1dabbcebacacbcaeadacdeb',
    '==============-+===+=-+====================',
  ],
  [
    'ecddaceabaccbcdaebcdbaacddeddebeaeaebcbd',
    'ecdaceabaccbcdaebcdbacddeddebeaeaebcbd',
    '===-==================-=================',
  ],
  [
    'ccebbdabcbdacaccccdeedaeeaebaadbbbbcaeee',
    'ccebbdabcbbdacaccccdeebdeabeeaebaaddbabbbcaeee',
    '==========+===========+=+=+========+=+========',
  ],
  [
    'bdbadabdceceadbabdcabbacdecacbdcaddeacad',
    'dbdbadabdeceadbad0cadbbacdecacbdcaddeacad',
    '+========-=======-=+==+====================',
  ],
  [
    'aaeacebbdccbbacaebbecabaadeddceaacadccde',
    'aaeacebbdccbbaacae0becaaadaeddceaacaadcce',
    '==============+===-+====-===+=========+===-=',
  ],
  [
    'dbabcaddddcdaecaadecaceadaaeddaddebeeddd',
    'ddbdabca0ddddaaec1adecaceadaaedaddeebeddd',
    '=+=+====+====--+===-+=============-====-=+====',
  ],
  [
    'eccccacdeccebbcadedbdbccaccdccbdcebebcae',
    '0ccccacdeccebbcadedb12ccaccdccbdcecbebcae',
    '-+===================--++============+======',
  ],
  [
    'addcbbcbccacedbedbaceceaaabbdcdabaabdcbeeaaebcaddebececbccceebbadeabcdaeabdbccdcaaaadceadbccdbebebbbacbaeecdddbcbecdaaea',
    'aeddcbbcbccacedbedbaceceaaab0dcdabaabdcbeaaebcaddebcecbccceebbadeabcdaeabdbccdcaaaadceadbeccdbebebbbacbaeecdddbcbecdaaea',
    '=+==========================-+============-==========-======================================+==============================',
  ],
  [
    'dcbdcedeecbbcedddebdadaccaecbacceacedcaddbcdddbadddbaecdececbdbdabecceaccaedeaaaedcbccbebbccacadadeccaeccdcecdebdbbbbdbe',
    'dcbdbcedeecbbceedddebdadacc0cbacceacedcaddbcdddbadddbaecdececbdbdabecceaccaedeaaaecdcb1cbebbccacadadeccaeccdececdebd2bbbdbe',
    '====+==========+===========--+======================================================+===-+=====================+=======-+======',
  ],
  [
    'ccadbcccebbbcbceaabdbeacadbbdebeadaccdeaccdcacbbbedacdbeaaaccddaedcaceeaeeacceebebbddebdadaaccedccccceabaacbdbdecbcdacda',
    'ccadbcccebbbcbceaabdbeac0dbbdebeadacacdeaccdcacbbbedacdbeaaaccddaedcaceeaeeacceebebbddebdadaaccedccccceabaacbdbdecbcdacda',
    '========================-+===========+====================================================================================',
  ],
  [
    'dbbbacaeddcacdedeadcbddcdccdaeccdeceabaceccadecbbbcccbaaceaaecabaeeacddbaadcbeeeccddaeccdadaacdbddcebdaccbacbdadaeceecdd',
    '0bbbeacaeddcacdedeadcbddcdccdaeccdceabaceccadecbbbcccbaaceaaecabaeeacddbaad1beeeccddaeccdadaacdbddcebdaccbbacbdadae2eecdd',
    '-+===+=============================-=========================================-+==============================+========-+=====',
  ],
  [
    'acbcbdadaddebbedecdaecbedecdccecccdeccbebebbababeaabccceabaeccdbdcbaeabddaabedeeebbcebcedceedcbacdcdbadecbdcebcbddeaaaab',
    'abcbdadaddebbdedecdaecbedecdccecccdecbebebbaabeaabcbcceabaeccdbdcbaeabddaabedeeebbcebcedceedcbacdcdbadecbdcebcbddeaaaab',
    '=-============+=======================-=======-=======+===================================================================',
  ],
  [
    'cdbacdcbeddabdbaadeeedabcbdbbdeeeacdbaebdbeaecbddabaeeccdeacbcdacbabadcadaddeacdccadccdecbeadbbaceebebceceadccbdebdadcca',
    'cdbacdcbededdabadbaadeeedabbdbbdeeeacdbaebdbeaecbdcdabaeccdeacbcdacadbadcadaddeacdccadccdecbeadcbbacee0ebce1eadccb2ebedadcca',
    '==========++===+===========-=======================+=====-===========-=+==========================+======-+====-+======-+==+======',
  ],
  [
    'bbceaebedcdceebbaaadbdbdbdcebdcbaeddceeedceddeaaccacbadbeacbabdabcbcdcabcccbbbceaceccacaeabaeabdacdadeaccaccedaabeacdddd',
    'bbebaeebe01eebbaaa2bdbddbd3bdcbaeddceeebdcddeaaccacbadbeacbbdabcbcedcabcccbbceaceccaabeabaedbdaacdadeac4ac5edaeacdddd',
    '==-=+==+==----++=======-+====+==--+============+==-=================-=======+=========-========-=+=====-+===+=======-+==-+===--=======',
  ],
  [
    'ecedddacbdacbeacddeebcbdceecabdadbeedaeeacdcbccaabeadcddcddaddccedcdabbecadaceecbbedcccddcccaebbecbbdccbceddccdbbabecbae',
    'eedddadcbdacbeacddceebcbceea0d1bdbeed2eeacd3bccaabeadcddcddaddcceddcdabecada4eecbbedcccddcccaebb5cbbdccbc6ddc7debbabebae',
    '=-=====+===========+=====-===-=-+=-++=====-+=====-+======================+====-=====-+===================-+========-+===-+=+=====-===',
  ],
  [
    'edcaaaaacdadadeedabceddbbaccbeabccdaaccdaeebdacbeadebcdaebddeeaccdbdddcbcaeedbeaacedebdaaaadacaaadebedadaadadbaeacaaeedc',
    'edcaaaaacdadaddedabcedadbbaccbeabcc0aaccdaeebdacdbeadebdcdae1ddeeaaccdbdddcbec2eedbea3c4adebdaaaadacaadeedadaadadbaeadaaeedc',
    '==============-+=======+============-+============+======+====-+=====+=========+=-+======-+=-++=============-==-=============-+======',
  ],
  [
    'cbedddbddecbbeaecdadebeabedbdcbabacbbdeedacebcadddbeeeeddccccdbcdccbebedddbaaabbdbaddcbbebdcbdbeadbdadbbbadbcebebbdbecaa',
    'acbedddcbddecbbeaecdabde0aeabeddbddbcbababbeedacebadd1beeaeeedccccbcdccbebbedddbaaabbdbadaddcbbebdcdb2adbdadebb3adbcebbebdbecbaa',
    '+======+=============+==-++=====+==++=====-==-=======-===-+===++===-====-========+==============++========-==-+======+==-+======-=+=====+==',
  ],
  [
    'fkcbdleabhiebakkgafeakageebeijhlchiglgld',
    'fkcbdleabhiebakkgafeakageeebeijhlachigl0ld',
    '==========================+======+=====-+==',
  ],
  [
    'giealfebdiggkkaliaeafihbgeabfkchdikfggdc',
    'giealfbdi0gkkaliaeafihbgeabfkch1ikfggdc',
    '======-===-+=====================-+=======',
  ],
  [
    'glkjcihkdfgggijabjjgggccbdkihjkffhcfkjfb',
    'glkjcihk0fgggijabjjggggccbd1ihjkffhcfkjfb',
    '========-+=============+====-+=============',
  ],
  [
    'egdkiahfcbebjldlchcflkhddceglahkhacafkib',
    'egdkiahfcbebj0dlchcflkhddceglhkhacafkib',
    '=============-+===============-==========',
  ],
  [
    'fjeigicjkcgghehbhahjejedbgcgcdbkbcbdhbgj',
    'fjeigicjkccgghehbhahjejedbgcgcdbkbcb0hbgj',
    '==========+=========================-+====',
  ],
  [
    'biikglhifgddbhejcbejagdeglgaaehcdleiafeh',
    'biik0lhifgddbhejcb1jagdeglgaae2dleiafgeh',
    '====-+=============-+===========--+======+==',
  ],
  [
    'djkgaadflfealkfjcaailaigcdcjbkkebcbhjbki',
    'djk0aadflfealbkfjca1il2igcdjbkebcbhjbki',
    '===-+=========+=====-+==-+====-===-=========',
  ],
  [
    'bhcgclgfghjdhkeekdcgdgeaeakbfjafhejjjjja',
    'bghc0lgf1hjdkeekd2gdgeaeakab34afhejkjjjja',
    '=--=+=+===-+===-=====-+========+=--++=====+=====',
  ],
  [
    'hlielikgfcehalhggajfjdblhejladckalbbkbbl',
    'hielikgfcelhalhggajfjdb01ejladckalbbkbbl',
    '=-=========+============--++===============',
  ],
  [
    'ckedblfebeglbghiaigkjffcdlfbgkkecfgldjae',
    'ckedblfebegbghiaigkjffcdlfbgkkecfgljae',
    '===========-========================-===',
  ],
  [
    'hildlejbbijbehfbkbkcgdlgejjgkaddbbhdecddbilchbihkkbkjkhfggfblhajfegekfhbjkhhgdkkaeeebhebjhflkdeflgdfgjljakjfeccjklkgaill',
    'hildlejbbijbehfbkbkcgdlgejjgkaddbbhecddbilchbih0kbkjkhfgg1blhajfegekfhbjkhhgdkkaeeebhebjhflkdeflgdf2jljakjfecfcjklkgaill',
    '===================================-============-+=========-+=========================================-+=========+==========',
  ],
  [
    'klachhkahljlkadgbibfljillhekggdaflabkhjlblbgkdcgcclkjhjdlghdlglcjigafghdklbkjeekhjghajbfbilghchhiilhfhigcbiekeghhefcfcgj',
    'klahhkahlj0kadgibfljllhekggaflabkhjlblbgkdgccl1jhjdlghdlglcjigafghdklbkjeekhjghajbfbilghchhiilhfhigcbiekeghhefcfcgj',
    '===-=======-+====-=====-=======-===============-====-+====================================================================',
  ],
  [
    'flecbidejggdcejhajbdjgkglgafehefihlielejgfidjlfjdjlgafddcccfddilkhgfbbigiehibakkjcblkhfdjlccjakblajflahakabgekfdkadckbdf',
    'flecbideggdcejhajbdjgkglgafehefihlielejgfidjlfjdjlgafddcccfddilkhgfdbbigiehibakkjcblkhfdjlccjakblajflahakabgekfdkadckbdf',
    '========-===========================================================+====================================================',
  ],
  [
    'bealhaccdfhkeffaejeailfdbegiclhhejekikjkhdeffdahddijlebbeghghclkicaklcaehfdgfjckkjiaeahlccjfdkblgeekcfdafeahklglifljfdai',
    'bealhaccdfhkeffaejeailfdbegiclhhejekikjgkhdeffd0hddijhlebbeghghclkicaklcaehfdgfjckkjiaeahlccjfdkblgeekcfdafeahklglifljfdai',
    '=======================================+=======-+=====+====================================================================',
  ],
  [
    'dajlfgdkfbbiadbcciadkgdflalgkjjhlgiljjbhhfdagbgheedkagdjglklhcecahclclkihhacaibahciecdlhlhgljegidbblehfbeglbkbdkkfifkaji',
    'dajlfhgdkfbbiadbcciad0gdflalgkjjhlgiljjbhhfdagbgheedkagdjglklhc1cahclclkihhacaibahciecdlhlhg2jegidbblehfbebglbkbdkkfifkaji',
    '=====+===============-+=========================================-+============================-+=============+===============',
  ],
  [
    'chifjegdilagdhffbkjclfbkabdjagcaeflagcelelcccjbldeghicdiafgfkllaakcgkjecgblldiicgabbeekedcehlheiikdbhaleahbgdkbdehakighc',
    'chifjiegkdilagdhffbkclf0kabdjagcakeflbadg1e2elcc3jbldelgihlicdiafdgfkllaakcbg4eje5gblldiicabcbeekecehlheiikdbhalecahbgdkbdek6ghc',
    '=====+==+===========-===-+=========+===+=+=-+=-+====-+=====+=+=+======+=========+=-++==-+========-==+=====-===============+=========--=-+===',
  ],
  [
    'ahljjaflaabldijecfglikkidbcabgbebhjklhjaeijhhhahghidjhhjdhcehbcgijhljlaahdddieijlhllfkfgghdagciceahaieeldcibacjdaijldccf',
    'ahl0jaflaabldijcfglkkidjbc1bgbehjklhjaejhhhahghijhjdahehcgijhlj2alahdddieijlhll3akfgjghdagciceajhaieeldciacj4aijldcgcf',
    '===-+===========-====-====+==-+====-========-=========-==-==+=-==-=======-+=+=============-++===+==========+=========-===-+======+==',
  ],
  [
    'idhecbkgiklljbhfcedhckaheikjkijbjcjhcbkgcflakaliaiefafidkgkafalbihfacfhieligcbegakllddlgidceeaeebkhaijlgdcbhjaagcggdgeef',
    'idhecbkgiikllkjbhfcdhkaheikkij0jclj1cbkgcflakaliaiefafigkaafalbihfachieligcbegailldd2gidc3eeebkh4ijlgdcbhjaa5cggdgeef',
    '=========+===+=====-==-======-===-+==+=-+===================--===+=========-===========-+====-+====+==--====-+===========-+========',
  ],
  [
    'lcdefkhakiibjacfgclkbdbiikldgdbgaekdlfhcdebhclidkjgabghbejffdcjbdlhdakhjaiceefgkhdjfjhlcgiglgaeekdgjjfjlikdaabhafgfhlgdc',
    'lcdefkhakiibjiacf01lkbdbikldgdbgaekdlfh2debhcl3dkjgea4ghbejkffdcjbdllhdakhjaiceefgkdjfjhlcgglg5ee6d7j8fjlikaabhafgfhlc',
    '=============+===--++======-==============-+======-+====+=-+=====+========+==============-========-===-+==-+=--+=+=====-==========--=',
  ],
  [
    'gkajddjaelkajeakliiaffecdcbbjakleceheflabhifhgihkajghkjdgjaflfheeiibifldbhjglblaebfchkhadblbjkecdbiihikbjdaebfljihflkkdj',
    'gajddj0elka1eakliaffecfdcbbjakleeheflkabh2fhgiajghkjdgjafilfheeiibifl3bhjglblaebfckhadblbjk4cdbiihikbdaebf5ihflkdj',
    '=-=====-+====-+=====-=====+=========-=====+===-+====--===========+===========-+============-=========-+=========-=====--+=====-==',
  ],
  [
    'uiWMcOYQIARMcAAfDcBJqNjkBgruoEXMOFueEXtL',
    'uiWMc0YQIARMcAADcBAJqNjBgruoEXMOFueEXtL',
    '=====-+=========-===+====-================',
  ],
  [
    'lKBwnuZGkDgzsFAkMPRbCXlXfALsBHoAKTxPFisI',
    'lKRBwnXuZGkDgszsFAk0PRbCXlXfALsBoAKTxPFisI',
    '==+===+======+=====-+============-==========',
  ],
  [
    'xNKOvpyWaEoEnqSzWnMIqtPfvcBkoncyZInIwmbB',
    'xNKOvpyWaEoEnqSzWnMIEq0PfvcBkoIncyZIIwmbB',
    '====================+=-+=======+=====-=====',
  ],
  [
    'jiFZbrSUWuHJMYqRAxOcrguAknObBUaXDdgHknyR',
    'j0FZbrSUWuHJMYqRAxOcrguAknObBUaXDdgHknyR',
    '=-+======================================',
  ],
  [
    'HTXFbhgViWFbEmWxNmuJEIqeyUSWHrOIRAvrQPHm',
    'HTXFbhViWFbFEmWxNmuJEHIeyUSWHrOIRAv0QPHm',
    '======-=====+=========+=-============-+====',
  ],
  [
    'VpCZcoDoniZgXuCSiJoSxqKvIUSibaGkuhcmLgSo',
    'VpCZcoDoniZcgXuCSiJoSxqgKvIUSbaGkuhc0LgSo',
    '===========+===========+=====-=======-+====',
  ],
  [
    'EonRYPfqeaWISnIfsMYpNNsugGnrisJUQkOGdxWr',
    'EonRYPfqeaW0SdnIsMY1NNsugGYnrisJUQkOGdWWr',
    '===========-+=+==-===-+======+===========-+==',
  ],
  [
    'SBerrCBeVuaxxcABEaRoXrAcZYcqSnMCmmiJstYv',
    'SBe0rBeV1qaBxx2ABEaRoXrAcZcqSnCmiJvstYv',
    '===+=--===-++=+==-+===========-====-==-==+====',
  ],
  [
    'eCjOfCfjcGafIdrSkfXvOCzcsSsXcOrtGLiJxWyV',
    'eCjO0LCfjcGafIdrSkfXvOCzcsSsXcOrtGLixWyV',
    '====-++==============================-====',
  ],
  [
    'KanjFFLDZfluaTTplACNyCTXwaqrBLdpCUHpkawj',
    'Knj0FLDZf1uUa2TplACNyCTXwaaqrBLdpCUHpka3j',
    '=-==-+=====-+=+=-+============+============-+=',
  ],
  [
    'hSWVTtDxosXkyxWUqKQrTPuWRpyQywKfWiCWZDmeekfQooYNYKGUAntCcnLKDuHlCYNVuHufanTlwOPyBUIlPCBhHXlpiVIWuFCKmvNLzsHXTkuqbMHNyDoY',
    'hSWVTtDxosXkyxWUqKQrTPuWRpyQywKfWiCWZDmeekfQooYNYKGUAOntCcnLKDuHlCYNVuH0fanTl1O2yBUIPCBhHXlpiVIW3FCKmvNLzsHXT4uqbMHNyDo',
    '=====================================================+=================-+=====-+=-+====-============-+============-+=========-',
  ],
  [
    'QVeXcjGWOYEialfdmgkWKgRWmdflKXdARnbpiwJpgRUbRzbkoTFmaraWkLiYHmLXXOWbYhZAXmstymPiFlrrkoSXxviQLBeRvaBqFOMhknEcVAFTgaNKgkAN',
    'QVXcjGWOYEiafdmgkWKgRWmdflXdARnbpiwJpgRUbRzbkoTFmaraWkLiYHmLXXOWbYhZAXmstymPiFlrrkoS0x1iQLBeRvaBqFOMhkn2cVAFTgoaNKgkAN',
    '==-==========-==============-==========================================================-+=-+================-+======+=======',
  ],
  [
    'ieKzHsQEwhXsQEWyYPAjszCVBcxDpfXgZBplLhxMtImcVzbHXZlCdiWJqsYfhjBOhAqAOqRRrXhktmLTdpjhegrvmJsQiUqDaaDmXtexsnnLCzVtOQekHAys',
    'ieKzHsQEwhXsQEWyYPAjszCVBcVxD0fXgZBp1LhxMtImcVzbHXZlCdiWJqsYfhjBOhAqAOqRRrXhktmLTdpjhegrvmJsQiUqDaaDmXtexsnnLCzVtOQekHAys',
    '==========================+==-+======-+====================================================================================',
  ],
  [
    'iLgKFIdDTiZLYtTLgJbfmniEbwDLsxVpMhQSKCzNEjzurZZGbCbgMeOqqhSLdYCqNCVkiqndqegDqxsCiRIJsVINskVxyMkzubqppEHJaFgtqWxnFadecves',
    'iLgKFId0TiZLYtTLgJbfmniEbwDLsxVDpMhQSKCzNEjzurZZGbCbgMeOqqhSLdYCNCVkiqndqegDquxsCiRIJsVIN1kVxyMkzuqppE2JaFgtqWxnFadecv3s',
    '=======-+=======================+================================-=============+===========-+========-====-+===============-+=',
  ],
  [
    'WFWhHFhxHGykdWXYRdRafpEswKHSPViWSHKjcKdJIbzMrWUeFAaQslAOJZKzPMmrKibzRdopcBkAnjdtJLioBcmCVuvBOUxDXcYeSlLtjrDyhikrzIhlKzjh',
    'WFWhiHFhxHGykdWXYRdRafpEsw0HSPViWSH1cKdJIbzMrWUeFAaQslAOJZzPMmrKibzRdopcBkAnjdtJLioBcmCVuvBOUHxDXcYeSlLtjrDyhikrzIhlKzjh',
    '====+=====================-+========--+======================-===================================+==========================',
  ],
  [
    'TFLqQENGSMBcCHUvOcQYZhHPwhBAwqzRfUWgFbXGgvEeSClXXlPTNLIuxvouvmxnqGdHvcxPfCikKnaPrpVZtdFwcNWbywUIzbyBOQbDAwOoJsUSlBexCIVK',
    'TFQLqQENGSMcCHSUvO0QYZhHPwhBAw1zRfUWgFbXGgvEeSClXklPTNLIuxzvouvm2n3GdHvcxPfCQikKnaPrpVZtdFwcNWwbw4byBOQbDAwOoJsUSl5exCIVK',
    '==+========-===+===-+===========-+==================-+========+=====-+=-+=========+=================+=-=---+================-+======',
  ],
  [
    'nNDeHhszFihRNXDjJihxkwVjDEmwsdgedpKUQDFsKXKSHmazaSAUBAkIWQqEkwOpiuFvBcQduoNdPPkNKFpZUECOkwDasNXpnpSDTRYmpQIOeUywrwhEkEVJ',
    'nNDeHhszFihRNXDjJKihxkwVjDEmwsdedpKUQNDFsKsX0SHmaza1AUBAkIWQqEwOpiuFvBcdQQduFoNdPPkNKFpZUEOkwDasNXpnpSDTRYmpQIOeUywrhEkEVJ',
    '=================+=============-======+====+=-+======-+==========-=========++===+=============-==========================-======',
  ],
  [
    'mXDkaWLAwnIstBxvAxMSZZWAuYGIcYCdrEkMgQGKqXXItwENQFODZDiqLLZhFxlgLRZBbUXSLscbcTiDxNXmBqZxjhJRXCEpvOGJcwDjWloEhMkBVEmeJJmn',
    'mXkaWLAwnIstBxvAxSZZA0YGI1YCdrEkMgGAKqXXItwENQFODZDiqLLZhFxlgLRZBbUXSLsvcbcTiDxNXmBqZxjhJRX2Ep34GJcwDjloEhM5BVEmeJJmn',
    '==-===============-===-=-+===-+========-=+===================================+===================-+==--++======-=====-+=========',
  ],
  [
    'IRzklKSWpvHbIqGQkQkftqlqqPCLZoPEFdGpxpLhNHQXocSZGPyMmDVAWcUSFupkSQYtZOucqkCucJVJPLyTVkUrDjKqINOKkUmllDVEpyzjenecZQPqrIIv',
    'IRzk0KSWpvHbI1GQkQktqlpqFqCLZoEF2GpxpLhNHQXocSZyMmDVAWc3SupkSYZOuc4kCucJVJPyTVkrDjKqI5OKkmllcDV6pyzjeneZQPqrIIv',
    '====-+========-+=====-===+=+=-====-==-+==============--========-+=-====-=-====-+========-====-======-+===-===+==-+=======-========',
  ],
  [
    'FffGBjyhkgGdTYEgIavHdALNNHWEQfDLQyUujxQvUcwAijZbUADNsiccypZlKyHwrhgmtOstSFPTKcRHxerzJHWrUFwNQlXLYkJBhSKyEIxpfRCtGTnWzZUh',
    'F0fGBjy1kgGdTYEgIavHdALNNHWEQfDLQyUujQvUcwAijZbUADNsicyplKyHwrhgmtOstSF2tTHKcHxerzJHWrUFwNQlfXLIYkJBhSKyEI3pfRCtGTnWzZUh',
    '=-+=====-+=============================-=================-==-===============-++=+==-===============+==+==========-+=============',
  ],
];
