export type Var = [string];
export type Wildcard = [[string]];
export type RouteDefinition = [method: 'GET' | 'POST' | 'DELETE' | 'PUT', path: (string | Var | Wildcard)[]];

export const definitions: RouteDefinition[] = [
  ['GET', ['ping']],
  ['GET', ['pong']],
  ['POST', ['ping']],
  ['POST', ['echo']],
  ['GET', ['info']],
  ['GET', ['types']],
  ['PUT', ['events']],

  ['GET', ['users']],
  ['GET', ['users', ['id']]],
  ['DELETE', ['users', ['id']]],
  ['POST', ['users', ['id']]],
  ['GET', ['users', ['id'], 'followers']],
  ['GET', ['users', ['id'], 'followers', ['friend']]],
  ['POST', ['users', ['id'], 'followers', ['friend']]],
  ['DELETE', ['users', ['id'], 'followers', ['friend']]],

  ['GET', ['posts']],
  ['GET', ['posts', 'search']],
  ['POST', ['posts']],
  ['GET', ['posts', ['post']]],
  ['POST', ['posts', ['post']]],
  ['DELETE', ['posts', ['post']]],

  ['GET', ['posts', ['post'], 'tags']],
  ['GET', ['posts', ['post'], 'tags', 'top']],
  ['GET', ['posts', ['post'], 'tags', ['tag']]],
  ['DELETE', ['posts', ['post'], 'tags', ['tag']]],
  ['POST', ['posts', ['post'], 'tags']],

  ['GET', ['api', 'collections']],
  ['POST', ['api', 'collections']],
  ['GET', ['api', 'collections', ['id']]],
  ['PUT', ['api', 'collections', ['id']]],
  ['POST', ['api', 'collections', ['id']]],
  ['DELETE', ['api', 'collections', ['id']]],

  ['GET', ['api', 'collections', ['id'], 'documents']],
  ['POST', ['api', 'collections', ['id'], 'documents']],
  ['GET', ['api', 'collections', ['collection'], 'documents', ['document']]],
  ['PUT', ['api', 'collections', ['collection'], 'documents', ['document']]],
  ['POST', ['api', 'collections', ['collection'], 'documents', ['document']]],
  ['DELETE', ['api', 'collections', ['collection'], 'documents', ['document']]],
  ['GET', ['api', 'collections', ['collection'], 'documents', 'search']],

  ['GET', ['api', 'collections', ['collection'], 'documents', ['document'], 'revisions']],
  ['GET', ['api', 'collections', ['collection'], 'documents', ['document'], 'revisions', 'find']],
  ['POST', ['api', 'collections', ['collection'], 'documents', ['document'], 'revisions']],
  ['GET', ['api', 'collections', ['collection'], 'documents', ['document'], 'revisions', ['revision']]],
  ['DELETE', ['api', 'collections', ['collection'], 'documents', ['document'], 'revisions', ['revision']]],

  ['GET', ['files', ['bucket'], [['path']]]],
  ['PUT', ['files', ['bucket'], [['path']]]],
  ['GET', ['files', 'list', ['bucket'], [['path']]]],
  ['GET', ['files', 'list', [['path']]]],

  ['GET', ['static', [['path']]]],
];

export const routes: [method: string, path: string][] = [
  ['GET', '/ping'],
  ['GET', '/pong'],
  ['POST', '/ping'],
  ['POST', '/echo'],
  ['GET', '/info'],
  ['GET', '/types'],
  ['PUT', '/events'],
  ['GET', '/users'],
  ['GET', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'],
  ['GET', '/users/123'],
  ['DELETE', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'],
  ['POST', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'],
  ['GET', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/followers'],
  ['GET', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/followers/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'],
  ['POST', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/followers/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'],
  ['DELETE', '/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/followers/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'],
  ['GET', '/posts'],
  ['GET', '/posts/search'],
  ['POST', '/posts'],
  ['GET', '/posts/jhasdf982lsd'],
  ['POST', '/posts/jhasdf982lsd'],
  ['DELETE', '/posts/jhasdf982lsd'],
  ['GET', '/posts/jhasdf982lsd/tags'],
  ['GET', '/posts/jhasdf982lsd/tags/top'],
  ['GET', '/posts/jhasdf982lsd/tags/123'],
  ['DELETE', '/posts/jhasdf982lsd/tags/123'],
  ['POST', '/posts/jhasdf982lsd/tags'],
  ['GET', '/api/collections'],
  ['POST', '/api/collections'],
  ['GET', '/api/collections/123'],
  ['PUT', '/api/collections/123'],
  ['POST', '/api/collections/123'],
  ['DELETE', '/api/collections/123'],
  ['GET', '/api/collections/123/documents'],
  ['POST', '/api/collections/123/documents'],
  ['GET', '/api/collections/123/documents/456'],
  ['PUT', '/api/collections/123/documents/456'],
  ['POST', '/api/collections/123/documents/456'],
  ['DELETE', '/api/collections/123/documents/456'],
  ['GET', '/api/collections/123/documents/456/revisions'],
  ['GET', '/api/collections/123/documents/456/revisions/find'],
  ['POST', '/api/collections/123/documents/456/revisions'],
  ['GET', '/api/collections/123/documents/456/revisions/789'],
  ['DELETE', '/api/collections/123/documents/456/revisions/789'],
  ['GET', '/files/user123-movies/2019/01/01/1.mp4'],
  ['PUT', '/files/user123-movies/2019/01/01/1.mp4'],
  ['GET', '/static/some/path/to/file.txt'],
];
