import {FromSlate} from '../FromSlate';
import * as traces from './traces';

describe('FromSlate', () => {
  describe('convert()', () => {
    test('single text paragraph', () => {
      const runner = traces.SlateTraceRunner.from(traces.variousOperations);
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      // runner.next();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
      runner.toNextCheckpoint();
      console.log(JSON.stringify(runner.state(), null, 2));
      console.log(JSON.stringify(FromSlate.convert(runner.state()), null, 2));
    });
  });
});
