import type {StickFieldOptions} from '../types';

export const defaultConfig: StickFieldOptions = {
  count: 2000,
  radius: 0.78,
  stickLength: 0.07,
  lineWidth: 3.8,
  rounding: 1,
  size: {base: 0.9, random: 0.35, wave: 1.4, waveFreq: 0.8, waveSpeed: 1.8, min: 0.15, max: 0.25},
  thickness: {base: 2.85, random: 0, wave: 1.3, waveFreq: 1.8, waveSpeed: 2.8, min: 3.55, max: 8},
  distance: {wave: 0.1, waveSpeed: 4.2},
  shapeOctaves: 3,
  shapeRoughness: 0.75,
  shapeSharpness: 1,
  pulse: 0.04,
  pulseSpeed: 0.75,
  flatten: 0,
  color: {wave: 1.45, random: 0, waveSpeed: 0.75},
  colorActive: 3,
  colorChangeSpeed: 2.45,
  magnetism: {base: 0.8, random: 0.05},
  fieldMode: 'radial',
  fieldDrift: 0,
  yawSpeed: 0.38,
  pitchAmp: 0.18,
  pitchSpeed: 0.35,
  perspective: 4.2,
  hideBack: false,
  cullDepth: 0.35,
  centerDrift: 0,
  centerDriftSpeed: 0.6,
  rays: false,
  rayWidth: 1,
  rayFrom: 0,
  rayTo: 1,
  rayAlphaNear: 0.4,
  rayAlphaFar: 0,
  fog: 0,
  twinkle: 0,
  twinkleSpeed: 4,
  vignette: 0,
  spin: 0,
  glow: 0,
  parallax: 0,
  additive: false,
  tiltMax: 0.65,
  reactToMouse: true,
  followMouse: true,
  followStrength: 0.6,
  followReach: 1.2,
  repelMouse: false,
  repelRadius: 140,
  repelStrength: 60,
};
