import type {StickFieldOptions} from '../types';

export const hedgehog: StickFieldOptions = {
  count: 444,
  radius: 0.78,
  origin: [0.78, 0.6],
  stickLength: 0.02,
  lineWidth: 4.8,
  rounding: 1,
  size: {base: 0.4, random: 0.35, wave: 1.4, waveFreq: 0.8, waveSpeed: 1.8, min: 0.15, max: 0.25},
  thickness: {base: 3.35, random: 0, wave: 1.3, waveFreq: 1.8, waveSpeed: 2.8, min: 3.55, max: 8},
  distance: {wave: 0, waveSpeed: 4.2},
  shapeOctaves: 1,
  shapeRoughness: 0,
  shapeSharpness: 1,
  pulse: 0,
  pulseSpeed: 0,
  flatten: 0,
  color: {wave: 1.45, random: 0, waveSpeed: 0.75},
  colorActive: 1,
  colorChangeSpeed: 2.45,
  magnetism: {base: 0.8, random: 0.05},
  fieldMode: 'radial',
  fieldDrift: 0,
  yawSpeed: 0.1,
  pitchAmp: 0.18,
  pitchSpeed: 0.35,
  perspective: 4.2,
  hideBack: true,
  cullDepth: 1,
  centerDrift: 0.08,
  centerDriftSpeed: 3,
  rays: true,
  rayWidth: 2.4,
  rayFrom: 0,
  rayTo: 0.5,
  rayAlphaNear: 1,
  rayAlphaFar: 0.14,
  fog: 0,
  twinkle: 1,
  twinkleSpeed: 4,
  vignette: 0,
  spin: 0,
  glow: 0,
  parallax: 0,
  additive: false,
  tiltMax: 0.65,
  reactToMouse: true,
  followMouse: false,
  followStrength: 0.6,
  followReach: 1.2,
  repelMouse: true,
  repelRadius: 265,
  repelStrength: 105,
};
