import type {SlateTrace} from '../traces';

export const slateBlockSplitsTrace: SlateTrace = {
  start: [
    {
      type: 'paragraph',
      children: [
        {
          text: '',
        },
      ],
    },
  ],
  operations: [
    {
      type: 'set_selection',
      properties: null,
      newProperties: {
        anchor: {
          path: [0, 0],
          offset: 0,
        },
        focus: {
          path: [0, 0],
          offset: 0,
        },
      },
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 0,
      text: 'T',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 1,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 2,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 3,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 4,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 5,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 6,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 7,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 8,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 9,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 10,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 11,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 12,
      text: 'g',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 13,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 14,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 15,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 16,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 17,
      text: '1',
    },
    {
      type: 'remove_text',
      path: [0, 0],
      offset: 17,
      text: '1',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 17,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [0, 0],
      offset: 18,
      text: '1',
    },
    {
      type: 'split_node',
      path: [0, 0],
      position: 19,
      properties: {},
    },
    {
      type: 'split_node',
      path: [0],
      position: 1,
      properties: {
        type: 'paragraph',
      },
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 0,
      text: 'T',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 1,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 2,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 3,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 4,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 5,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 6,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 7,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 8,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 9,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 10,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 11,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 12,
      text: 'g',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 13,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 14,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 15,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 16,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 17,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [1, 0],
      offset: 18,
      text: '2',
    },
    {
      type: 'split_node',
      path: [1, 0],
      position: 19,
      properties: {},
    },
    {
      type: 'split_node',
      path: [1],
      position: 1,
      properties: {
        type: 'paragraph',
      },
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 0,
      text: 'T',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 1,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 2,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 3,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 4,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 5,
      text: 'i',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 6,
      text: 's',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 7,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 8,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 9,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 10,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 11,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 12,
      text: 'g',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 13,
      text: 'r',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 14,
      text: 'a',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 15,
      text: 'p',
    },
    {
      type: 'remove_text',
      path: [2, 0],
      offset: 15,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 15,
      text: 'p',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 16,
      text: 'h',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 17,
      text: ' ',
    },
    {
      type: 'insert_text',
      path: [2, 0],
      offset: 18,
      text: '3',
    },
    {
      type: 'split_node',
      path: [2, 0],
      position: 19,
      properties: {},
    },
    {
      type: 'split_node',
      path: [2],
      position: 1,
      properties: {
        type: 'paragraph',
      },
    },
  ],
  checkpoints: [
    2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
    64, 65, 66, 68,
  ],
};
